version: '3.9'
services:
  web:
    env_file:
      - .env
    build: 
      no_cache: true
      context: . 
    ports:
      - "8080:8080"
    volumes:
      - ./data:/bookcaster/data
    command: npm run start
