web:
  environment:
    - ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - S3_ENDPOINT_URL=https://s3.us-west-1.wasabisys.com/
    - AUDIO_BOOKS_USER
    - AUDIO_BOOKS_PASSWORD
  build: .
  ports:
    - "8080:8080"
  volumes:
    - .:/bookcaster
  command: npm run dev:watch
